#!/usr/bin/env bash

web_server=nginx


/usr/bin/certbot renew --quiet --agree-tos --pre-hook "service $web_server stop" --post-hook "service $web_server restart" >> /var/log/certbot-renew-time.log
# mail -s "CERTBOT Renewals" certbotrenew@example.com < /var/log/certbot-renew.log
exit 0
